// Date: 6/1/2014 1:51:39 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package cliffracerx.mods.cliffieswars.src;

import net.minecraft.client.Minecraft;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.ResourceLocation;

public class ModelRPGLauncher extends ModelBase
{
  //fields
    ModelRenderer Handle;
    ModelRenderer Barrel;
    ModelRenderer Trigger;
    ModelRenderer Light;
  
  public ModelRPGLauncher()
  {
    textureWidth = 32;
    textureHeight = 32;
    
      Handle = new ModelRenderer(this, 0, 0);
      Handle.addBox(-1F, 0F, -1F, 2, 8, 2);
      Handle.setRotationPoint(0F, 0F, 0F);
      Handle.setTextureSize(64, 32);
      Handle.mirror = true;
      setRotation(Handle, 0F, 0F, 0F);
      Barrel = new ModelRenderer(this, 8, 0);
      Barrel.addBox(-2F, -2F, -2F, 4, 22, 4);
      Barrel.setRotationPoint(1F, -2F, 0F);
      Barrel.setTextureSize(64, 32);
      Barrel.mirror = true;
      setRotation(Barrel, -1.570796F, 1.570796F, 0F);
      Trigger = new ModelRenderer(this, 0, 10);
      Trigger.addBox(-0.5F, 0F, -0.5F, 1, 4, 1);
      Trigger.setRotationPoint(-4F, 0F, 0F);
      Trigger.setTextureSize(64, 32);
      Trigger.mirror = true;
      setRotation(Trigger, 0F, 0F, -0.7853982F);
      Light = new ModelRenderer(this, 0, 10);
      Light.addBox(-0.5F, -0.5F, -0.5F, 1, 1, 1);
      Light.setRotationPoint(3F, -4F, -2F);
      Light.setTextureSize(64, 32);
      Light.mirror = true;
      setRotation(Light, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5, Minecraft mc, HandheldRocketLauncher item)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    mc.renderEngine.bindTexture(new ResourceLocation(
            "cliffieswarsmod:textures/models/items/"+item.col+"RPGLauncher.png"));
    Handle.render(f5);
    Barrel.render(f5);
    Trigger.render(f5);
    Light.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity ent)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, ent);
  }

}
